# Generated by Django 3.1.3 on 2020-11-29 20:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('codemeli', models.BigIntegerField(max_length=15)),
                ('phone', models.BigIntegerField(max_length=20)),
                ('car_name', models.CharField(max_length=20)),
                ('car_model', models.CharField(max_length=4)),
                ('car_pelak', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('person_code', models.IntegerField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='safar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mamoriat', models.CharField(max_length=50)),
                ('maghsad', models.CharField(max_length=300)),
                ('mabda', models.CharField(max_length=300)),
                ('datetime_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_stop', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_def', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_now', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.person')),
            ],
        ),
    ]
