# Generated by Django 3.1.2 on 2020-12-16 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_safarbackup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safar',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='driver.driver'),
        ),
        migrations.AlterField(
            model_name='safar',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='driver.person'),
        ),
    ]
