# Generated by Django 3.1.3 on 2020-11-26 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=20)),
                ('car_model', models.CharField(max_length=4)),
                ('car_pelak', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('codemeli', models.IntegerField(max_length=10)),
                ('phone', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('person_code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='safar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mamoriat', models.CharField(max_length=50)),
                ('maghsad', models.CharField(max_length=300)),
                ('mabda', models.CharField(max_length=300)),
                ('datetime_start', models.DateTimeField(verbose_name='date published')),
                ('datetime_stop', models.DateTimeField(verbose_name='date published')),
                ('datetime_def', models.DateTimeField(verbose_name='date published')),
                ('datetime_now', models.DateTimeField(verbose_name='date published')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.driver')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.person')),
            ],
        ),
    ]
