# Generated by Django 3.1.3 on 2020-11-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='codemeli',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.IntegerField(max_length=15),
        ),
    ]
