# Generated by Django 3.1.3 on 2020-11-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20201126_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.PositiveIntegerField(max_length=50),
        ),
    ]
