# Generated by Django 3.1.3 on 2020-11-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20201126_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='codemeli',
            field=models.BigIntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.BigIntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_code',
            field=models.IntegerField(max_length=8),
        ),
    ]
